### ISSUE TITLE
Looking good - a few suggestions

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#1]
- Don't make bear logo cover the whole screen - put it on the side (smaller) with some sort of text box on the right.   In text box: 

The MacArthur-Bates Communicative Development Inventories (CDIs), and the corresponding Spanish-language Inventarios, are parent report instruments which capture important information about children's developing abilities in several domains of early language, including vocabulary comprehension, production, gesture use, and early grammar. The CDIs have been adapted in many different languages (see Adaptations) and both long and short forms are available for use with children 8 to 36 months of age. The English and Spanish versions are distributed by Brookes Publishing Company (www.brookes.com).

Development of these instruments was made possible by support of the MacArthur Research Network on Early Childhood Transitions provided by the John D. and Catherine T. MacArthur Foundation.

This site is sponsored by the MacArthur-Bates CDI Advisory Board.
- The second sliding panel is "Announcements and news!"
- The third sliding panel is "Contact us"
- Can we have 4 bubbles at the bottom (from left to right): Scoring Program, English and Spanish Forms, Adaptations in Other Languages, Lexical Norms

**Comment by esalling23** [comment]
Any way we can cut down the text on the front slide? A lot of that could be put into a longer "About" section -- the carousel content should be 2-3 sentences max.

**Comment by vmarchman** [comment]
ok. sure:  How's this:

The MacArthur-Bates Communicative Development Inventories (CDIs), and the corresponding Spanish-language Inventarios, are parent report instruments which capture important information about 8 to 36-month-old children's language and communicative development.

Full text as in #1 could go in About.
