### ISSUE TITLE
Scoring Program download page??

### ISSUE THREAD

**Issue by esalling23** [esalling23/CDIWebsite#16]
I do not have access to a server to use for a submission page that can then redirect to the download -- should I leave this as an incomplete portion of the website?

I will spend some time attempting to make a server via Node.js

**Comment by vmarchman** [comment]
hmm.  we should talk about this. this download itself is just a download of
an self-extracting executable file.

The only tricky part is that it links to a google doc that makes people
provide their
name/email, etc.  but my friend Lucy set that up and she thought it was
pretty easy.

**Comment by esalling23** [comment]
okay but the form right now uses PHP which is currently being taken over by node.js, so if I use the same methods Lucy did, it might break in a year or so

I'm looking into node to see if I can have it just do the same thing without requiring a server necessarily

**Comment by vmarchman** [comment]
awesome.  Yes, if you can give me the same functionality using a more
modern (robust) language, that would be great.
