### ISSUE TITLE
stats?

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#17]
Can we get periodic google stats on traffic to the site?

**Comment by esalling23** [comment]
Before I can set this up we need a set URL from wherever it will be posted upon completion

**Comment by vmarchman** [comment]
It will live in the same place as the old one:

http://mb-cdi.stanford.edu/

It's not there now, obviously, but that's where it will go.

That's the vanity url.

**Comment by esalling23** [comment]
Okay i will look into this a bit more

**Comment by esalling23** [comment]
Okay I will get thi set up, I accidentally set it up with my email so I'm going to either need a google account for the project that already exists, or I can set one up and send you the information for all of it

**Comment by vmarchman** [comment]
Here's the email that I use for the scoring program:

macbatescdi@gmail.com

Do you need the password?

**Comment by esalling23** [comment]
yes i do so i can make the google statistics account while signed into that gmail

**Comment by vmarchman** [comment]
cdidatabase

**Comment by esalling23** [comment]
this password doesnt work

**Comment by esalling23** [comment]
it is CDIdatabase
