### ISSUE TITLE
broken link - resources page

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#18]
This link is broken:
 Infant and Child Development Laboratory, San Diego State University

**Comment by esalling23** [comment]
Will be fixed on next commit

**Comment by esalling23** [comment]
The link is broken on the original site for me, I fixed a typo in it but it still will not open for me, I don't have permissions --

**Comment by vmarchman** [comment]
Yeah, sorry.  I've emailed the person and asked for the updated link.  So, we can't do anything about this one now.

**Comment by vmarchman** [comment]
Ok, turns out that she doesn't have a working link. We can link to her facebook page for now.
https://www.facebook.com/SDBabylab

(she told me she needs a new website - soooooo maybe another job for you?!?! if you want it!)

**Comment by esalling23** [comment]
SUre!! Hahah okay ill fix this now!
