### ISSUE TITLE
Adaptations

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#20]
Adaptations
Add new second sentence under Adaptations noting that the authors of each version should be contacted directly for information.
Great that you combined the 2 sources of info on foreign versions
I wonder if the main heading "Adaptations" should be changed to Other Languages"?

**Comment by esalling23** [comment]
did you mean for me to replace the current 2nd sentence?
check commit -

**Comment by vmarchman** [comment]
Yes, the first paragraph reads fine as you have it now.

But, the rest of that section should be changed a bit.  The info about Dale & Penfold (2011) should be integrated with the following paragraph as follows.  This is how the text should read:

A survey of all known projects was conducted in 2011, and a complete listing of those projects is available for download here: (BOLD LINK) Dale & Penfold (2011). In some cases, this survey has more extensive information on many of the projects than is included in the links to the left. However, users should keep in mind that new projects have been added since the survey was conducted, and we will do our best to post the most up-to-date information here if a project is underway for any specific language.  You may also contact Philip Dale (BOLD LINK) for more information.

Developers of Adaptations of the CDIs should remember that the CDI instruments are copyrighted and creation of new adaptations of these instruments in other languages requires permission of the CDI Advisory Board.

The CDI Advisory Board has formulated guidelines for obtaining authorization for adapations of the CDIs into other languages, as can be found here.

We also suggest that before undertaking an adaptation project, investigators should read Adaptations, not Translations!
