### ISSUE TITLE
home page link

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#21]
Home
I see that you can get to the home page by clicking on the logo. Should you ad a  Home link to the left of Advisory Board in the main headings?

**Comment by esalling23** [comment]
I thought that was redundant, and would at this point throw off a lot of the responsiveness of the nav-bar
If necessary I can add it, but most sites rely on a brand image as their "home" link

**Comment by vmarchman** [comment]
Ok, we can just tell him that it is not standard practice.
