### ISSUE TITLE
English short forms

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#23]
Short forms:
For English, it does not indicate that paper copies available thru my office. Should be just like you have for the Spanish short forms - but leave off the fax # for both.

VM to give you updated text for this.

**Comment by esalling23** [comment]
updating this, check next commit to be sure fixes are correct --

**Comment by vmarchman** [comment]
Update text as follows:  

One page short form versions of the English-language CDI instruments are also available. The infant form (Level I) is comprised of a 89-word vocabulary checklist with separate columns for comprehension and production. Two Words & Sentences versions (Level IIA and Level IIB) contain a 100-word productive vocabulary checklist and a question about combining words. The short forms can serve as an alternative to the full version when rapid assessment of a child's language level is needed or when parental literacy is low. 

They may be ordered at a cost of $.35 each from: 
Larry Fenson, Department of Psychology, 5500 Campanile Drive, San Diego State University, San Diego, Ca 92182-4910 
Phone: (619) 594-6614 
Email: lfenson@gmail.com

Update!: Announcing new downloadable fillable pdf versions of the English-language Short Forms! These can be downloaded and emailed to parents to complete on their own computers or tablets. Please advise parents that they will need the latest version of Adobe Reader (Version X or higher) to save the completed forms and email them back to you. To export the data into csv format for scoring, you will need to purchase Adobe Acrobat, which is available for academic discount through most institutions. Please contact Virginia Marchman.

**Comment by vmarchman** [comment]
Add link to me on contact line:  For more information, contact (BOLD LINK) Virginia Marchman.
