### ISSUE TITLE
email links?

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#25]
Larry says: Email links:
For me, all email links open in Outlook. Just my setup?

That's him, right?

**Comment by esalling23** [comment]
They should be opening in the default mail application on the person's computer -- I think it may just be him but we can ask him for more information and see whats up

**Comment by vmarchman** [comment]
Yeah - I realized nothing happens when I click on those links.

**Comment by esalling23** [comment]
this is intriguing because they work perfectly on my computer, and open up an email on my mail app
what browser are you using, and does anything at all happen when you click on them?

**Comment by vmarchman** [comment]
In Chrome - Nothing happens when I click the email addresses, but I do see the link in my nav bar (as I do any link).  I looked in settings and I couldn't find anything about what to do when you click on an email link.....
