### ISSUE TITLE
links on footer

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#26]
These links are broken/don't go anywhere:

© 2015 CDI Advisory Board 

Privacy

Terms

**Comment by esalling23** [comment]
I dont have any sites to link those to, I put them in just to set up the Footer initially.
We have a copyrights page but no "privacy" or "terms" -- should i remove the links or do we have something to put there?

The CDI Advisory Board should be linking to a "Copyright" page

**Comment by vmarchman** [comment]
Let's just remove "privacy" and "terms". 

Can't we just say "Copyright 2015 MacArthur-Bates CDI Advisory Board" - like it is on the original site?
