### ISSUE TITLE
Scoring program page

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#29]
Fix this typo: chilren 30-37

Fix text size in top section.

Can we get a copyright symbol?

Should be "Palabras y Gestos"

**Comment by esalling23** [comment]
check next commit!!

**Comment by vmarchman** [comment]
Much better! Sorry: more typos:

McArthur-Bates Communicative Development Inventaries

Delete: "newly available" in "and the newly available, Level III"
