### ISSUE TITLE
links distinct color before hover?

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#31]
From Philip: It’s pretty standard to have hyperlinks distinctively marked, either by color or underlining. The links in this design become clear once you hover over them with a mouse, but not until then. How about either a third color or underlining?

**Comment by esalling23** [comment]
Which links in particular -- they should be a bolder font in the text, and bolder w/ underline animation outside of text sections

**Comment by vmarchman** [comment]
Yes, they should either be a different color or be bold in the text.  It's just that you can't find where the links are unless you hover.

**Comment by esalling23** [comment]
they are all bolded

**Comment by vmarchman** [comment]
Not in this latest commit?
