### ISSUE TITLE
Lexical norms links - to new internal link, not wordbank external link

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#34]
New text for front page: 

Two projects, CLEX and Wordbank, compile responses from many different CDI administrations in many different languages.  Each provides exciting new resources for the construction of crosslinguistic lexical norms for many different research purposes. (Note: For clinical purposes, users should refer to the norming information provided for each language.) Click below to learn more about these resources!

Link to NEW Lexical Norms page.

Then in NEW Lexical Norms page.

Two recent projects compile responses from many different CDI administrations in many different languages.  Each provides exciting new resources for the construction of crosslinguistic lexical norms for many different research purposes. 

---

1st box
CLEX (Cross Linguistic Lexical Norms) is a web service where everyone interested in children’s early languages acquisition can search for norms in children’s early language based on studies from different MacArthur-Bates Communicative Development Inventories (CDIs) studies. It is currently possible to search in Danish, Croatian, German, Italian, Mexican Spanish, Norwegian, American English, Russian, Turkish and Swedish.  See more here:  http:www.cdi-clex.org/

2nd box
Wordbank is an open database of information about children's vocabulary growth.
Wordbank archives data from the MacArthur-Bates Communicative Development Inventory (MB-CDI), a family of parent-report questionnaires. Wordbank enables researchers to analyze MB-CDI data in terms of aggregate vocabulary, individual items, demographic variables, and more. It provides interactive visualizations, exploratory reports, and data export tools.
Wordbank is open access! You can use the wordbankr package to access Wordbank data from R.  Learn more about Wordbank here:  http://wordbank.stanford.edu

Important Disclaimer: Wordbank visualizations of norming data reflect the currently available data, dynamically combined from different sources that may not be identical to those included in the norming samples for a particular instrument. In particular, users should be aware that the values provided by Wordbank for English and Spanish are based on different participants and are estimated following different computational procedures than the values published in the User’s Guide and Technical Manuals (Fenson et al., 2007; Jackson-Maldonado et al., 2003) and applied in the CDI Scoring program (Marchman, 2013).

In general, we do not recommend that Wordbank-generated norming values be used for research or clinical purposes in which the goal is to evaluate children's performance in reference to an established normative standard (e.g., determining the mean words produced percentile of a group of children in a study; classifying whether the performance of an individual child falls below the 10th percentile). For these types of applications in English and Spanish, users should refer to the norms and guidelines published in the manuals for those languages (available from Brookes Publishing Co). For similar applications in other languages, users should refer to the appropriate manuals and norming information.

**Comment by esalling23** [comment]
am i making a new page? just basic format?

**Comment by vmarchman** [comment]
Yup.  Just a single panel - like the scoring program page.  Intro paragraph, then two boxes (see #1 and 2 above).  Bolding links and "Important Disclaimer".
