### ISSUE TITLE
Forms page redo

### ISSUE THREAD

**Issue by esalling23** [esalling23/CDIWebsite#5]
fix break

**Comment by esalling23** [comment]
still 2 buttons not working -- extend to the 12th

**Comment by vmarchman** [comment]
1) tab name for form sub-page still says McArthur
2) are these the new graphics?  they look terrible...:-(
3) order of drop down should be from left to right:  Long forms, Short Forms, CDI III
4) content of Spanish long = Spanish short; i.e., they are switched
