### ISSUE TITLE
link to Wordbank - Lexical Norms page

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#53]
should be http://  (not https://)

**Comment by esalling23** [comment]
where is this

**Comment by vmarchman** [comment]
Wordbank is an open database of information about children's vocabulary growth. Wordbank archives data from the MacArthur-Bates Communicative Development Inventories in many different languages. Wordbank enables researchers to analyze MB-CDI data in terms of aggregate vocabulary, individual items, demographic variables, and more. It provides interactive visualizations, exploratory reports, and data export tools. Wordbank is open access! You can use the wordbankr package to access Wordbank data from R. Learn more about Wordbank! <------THIS LINK
