### ISSUE TITLE
short form images

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#59]
VM to create images of English and Spanish short forms with watermark.

EMS to disable right-clicking for these images.

**Comment by esalling23** [comment]
cannot disable right click for image, can only for whole page

**Comment by vmarchman** [comment]
Updated new image files with watermark.

**Comment by vmarchman** [comment]
Let's go ahead and disable for whole page.  Why not?

**Comment by esalling23** [comment]
no one will be able to copy text or anything like that, if the email links do not open with their mail application they cannot click to copy those links, etc

**Comment by vmarchman** [comment]
I think just having the images with the watermarks is enough.
