### ISSUE TITLE
Color scheme/General Design fixes

### ISSUE THREAD

**Issue by esalling23** [esalling23/CDIWebsite#6]
Comment here with fixes for design and color scheme!

**Comment by vmarchman** [comment]
Advisory board page looks great for me.  Not sure how the brown and the blue are working together though.  I like having the bates thing separated, but should it be it's own page, rather than at the bottom of the main page?  (My doodle is gone :-()  Like your new system of dates!  Will wait to see how things pan out over the next couple of days!!!!

**Comment by vmarchman** [comment]
I'm loving the "lighter" look!  What do you think!?  And, I love the underscore over hover!  Very classy!

**Comment by esalling23** [comment]
Glad you like that!! I thought it would add the right amount of flash to
the site.

More to come tonight!

**Comment by vmarchman** [comment]
Random suggestions: 
1) make wordle a bit bigger
2) remove comma after Inventories in top paragraph - looks funny to end line with comma
3) make text of 4 bubble paragraphs just a bit bigger
4) make text for the 3 mini-nav bar buttons a bit bigger - and hover goes to brown, not the new classy underline thing

**Comment by esalling23** [comment]
1. I don't think I'll be able to I'll try
2. Can do.
3. I'll increase the font size
4. The hover underline would look odd I thought but I'll try it

**Comment by esalling23** [comment]
wordle is giving issues but im trying to make it a bit bigger -- screwing up the responsiveness that's all

**Comment by vmarchman** [comment]
don't worry about it too much then.....

**Comment by vmarchman** [comment]
Advisory board page:  Now the rows are much farther apart.  They look better when they are closer together.

**Comment by vmarchman** [comment]
Typo in Advisory Board page:
Sand Diego State University  - should be San Diego

Email links in board page should be brown, not green.  and they disappear on hover.
