### ISSUE TITLE
font color

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#68]
- I would consider making the brown color in the palette a little darker, or even making it black, for readability... it's a little unusual to have a primary text element have a non-black color like that.

**Comment by esalling23** [comment]
its not unusual at all to have text be a non-black color.....and that would look really weird....i can make it a darker brown --

**Comment by esalling23** [comment]
check the new color

**Comment by vmarchman** [comment]
Ok.  Did you mean for the 4 links under the nav bar to go down in the
footer?

**Comment by esalling23** [comment]
yeah it makes the site look cleaner i think

**Comment by vmarchman** [comment]
Yeah, but we wanted Announcement and News to be really salient, and now
it's all the way at the bottom of the page....

**Comment by vmarchman** [comment]
and you won't let me add News! to the top Nav Bar?

**Comment by esalling23** [comment]
how about a news link underneath the main blurb on the front page too?

**Comment by vmarchman** [comment]
Yes, let's see where we can put this!!!

**Comment by esalling23** [comment]
check!

**Comment by vmarchman** [comment]
It's fine. Let's leave it for now.
