### ISSUE TITLE
replace first bubble picture with this one

### ISSUE THREAD

**Issue by vmarchman** [esalling23/CDIWebsite#72]
![latinobaby](https://cloud.githubusercontent.com/assets/7682636/11257091/6a95c07a-8e04-11e5-9ab7-bd0accfe9f09.png)

**Comment by vmarchman** [comment]
or this one:
![latinoboy](https://cloud.githubusercontent.com/assets/7682636/11260056/608a93cc-8e1c-11e5-8e3b-2ce28d3d0c38.JPG)

I like this one better though

![latinogirl](https://cloud.githubusercontent.com/assets/7682636/11260031/18406c90-8e1c-11e5-9ea9-11bbe12c44ea.jpg)

**Comment by vmarchman** [comment]
I tried to do it and the images got all squished!  Help!

**Comment by esalling23** [comment]
Will check this out today after work!

**Comment by vmarchman** [comment]
Great!  Do you want me to commit what I did?  Did you do stuff after your
last commit yesterday?

**Comment by esalling23** [comment]
No I didn't - if you only changed the picture then don't commit and I'll
just switch out the pictures

**Comment by vmarchman** [comment]
The picture looks squished.  :-(

**Comment by esalling23** [comment]
can you send me the image on slack- something is up with the file when i try to save it from here thanks!

**Comment by vmarchman** [comment]
It should be in the images folder.

**Comment by esalling23** [comment]
its not, can you try pushing again?
i cant find it on my end

**Comment by vmarchman** [comment]
Here they are.  They are in images/babies.

**Comment by esalling23** [comment]
i am pulling and not receiving any images - can you make sure you added the files to your commit, and then push

**Comment by vmarchman** [comment]
did you get them now?

**Comment by esalling23** [comment]
yes but the latinogirl doesnt work - something up with the jpeg format? i keep getting an error

**Comment by vmarchman** [comment]
​I just committed with a new pic that is cropped and changed to png​

**Comment by esalling23** [comment]
personally i think its a lot lower quality than the other pictures so it looks odd, but its there now!

**Comment by vmarchman** [comment]
You're right. Let's use  For me, it's all messed up now.....

**Comment by vmarchman** [comment]
HispanicGirl2.png

**Comment by vmarchman** [comment]
shit! - I think I just committed an old index.htm.....

**Comment by esalling23** [comment]
no worries!!

**Comment by vmarchman** [comment]
Pic looks great!  but now my "more here" etc are in the middle of the
text!!!!

**Comment by esalling23** [comment]
fixed!!~

**Comment by vmarchman** [comment]
Awesome!

**Comment by vmarchman** [comment]
Can we move Liz's picture to more center? (sorry!)

**Comment by esalling23** [comment]
got it!!

**Comment by vmarchman** [comment]
Awesome!  Thanks for doing this!

Maybe under the wordle?

got it!!
